apiVersion: v1
kind: Pod
metadata:
  name: nginx-taint
spec:
  nodeSelector:
    gpu: "true"

  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: NoSchedule