apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: demo 
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    purpose: demo 
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - demo
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: pod-2
    image: nginx